-- ============================================================
-- IMPORTADORA A&N
-- Módulo seguro de ventas, inventario y liquidaciones
-- Fecha: 2026-07-28
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. TABLA PRINCIPAL DE VENTAS
-- ------------------------------------------------------------

create table if not exists public.ventas (
    id uuid primary key default gen_random_uuid(),
    numero bigint generated by default as identity unique,
    fecha timestamptz not null default now(),

    cliente_nombre text,
    cliente_telefono text,
    metodo_pago text,
    observacion text,

    estado text not null default 'completada'
        check (estado in ('pendiente', 'completada', 'anulada')),

    total_venta numeric(12,2) not null default 0
        check (total_venta >= 0),

    total_costo_proveedor numeric(12,2) not null default 0
        check (total_costo_proveedor >= 0),

    total_otros_gastos numeric(12,2) not null default 0
        check (total_otros_gastos >= 0),

    total_ganancia numeric(12,2) not null default 0,

    creado_por uuid not null default auth.uid()
        references auth.users(id),

    creado_en timestamptz not null default now(),

    anulada_por uuid references auth.users(id),
    anulada_en timestamptz,
    motivo_anulacion text
);

comment on table public.ventas is
'Cabecera de cada venta. Los totales se calculan desde sus detalles y quedan congelados históricamente.';


-- ------------------------------------------------------------
-- 2. DETALLE DE PRODUCTOS VENDIDOS
-- ------------------------------------------------------------

create table if not exists public.detalle_ventas (
    id uuid primary key default gen_random_uuid(),

    venta_id uuid not null
        references public.ventas(id)
        on delete restrict,

    sku text not null
        references public.productos_publicos(sku)
        on update cascade
        on delete restrict,

    -- Copias históricas para no alterar ventas anteriores
    producto_nombre text not null,
    codigo_modelo text,
    color_caja text,
    imagen_principal text,

    tipo_precio text not null
        check (tipo_precio in ('minorista', 'mayorista', 'personalizado')),

    cantidad integer not null
        check (cantidad > 0),

    precio_sugerido_unitario numeric(12,2) not null
        check (precio_sugerido_unitario >= 0),

    precio_venta_unitario numeric(12,2) not null
        check (precio_venta_unitario >= 0),

    precio_base_historico numeric(12,2) not null
        check (precio_base_historico >= 0),

    factor_costo_historico numeric(12,4) not null
        check (factor_costo_historico >= 0),

    costo_proveedor_unitario numeric(12,2) not null
        check (costo_proveedor_unitario >= 0),

    otros_gastos numeric(12,2) not null default 0
        check (otros_gastos >= 0),

    subtotal numeric(12,2)
        generated always as (
            round(cantidad * precio_venta_unitario, 2)
        ) stored,

    descuento_total numeric(12,2)
        generated always as (
            round(
                greatest(
                    (cantidad * precio_sugerido_unitario)
                    - (cantidad * precio_venta_unitario),
                    0
                ),
                2
            )
        ) stored,

    costo_proveedor_total numeric(12,2)
        generated always as (
            round(cantidad * costo_proveedor_unitario, 2)
        ) stored,

    ganancia_real numeric(12,2)
        generated always as (
            round(
                (cantidad * precio_venta_unitario)
                - (cantidad * costo_proveedor_unitario)
                - otros_gastos,
                2
            )
        ) stored,

    creado_en timestamptz not null default now()
);

create index if not exists detalle_ventas_venta_id_idx
    on public.detalle_ventas(venta_id);

create index if not exists detalle_ventas_sku_idx
    on public.detalle_ventas(sku);

comment on table public.detalle_ventas is
'Productos incluidos en una venta. Guarda precio base, factor, costo y precio real como fotografía histórica.';


-- ------------------------------------------------------------
-- 3. MOVIMIENTOS DE INVENTARIO
-- ------------------------------------------------------------

create table if not exists public.movimientos_inventario (
    id uuid primary key default gen_random_uuid(),

    sku text not null
        references public.productos_publicos(sku)
        on update cascade
        on delete restrict,

    venta_id uuid
        references public.ventas(id)
        on delete restrict,

    tipo text not null
        check (tipo in (
            'venta',
            'anulacion_venta',
            'ajuste_entrada',
            'ajuste_salida'
        )),

    cantidad integer not null
        check (cantidad <> 0),

    stock_anterior integer not null,
    stock_nuevo integer not null
        check (stock_nuevo >= 0),

    observacion text,

    creado_por uuid not null default auth.uid()
        references auth.users(id),

    creado_en timestamptz not null default now()
);

create index if not exists movimientos_inventario_sku_idx
    on public.movimientos_inventario(sku);

create index if not exists movimientos_inventario_venta_id_idx
    on public.movimientos_inventario(venta_id);


-- ------------------------------------------------------------
-- 4. LIQUIDACIONES ENTREGADAS AL PROVEEDOR
-- ------------------------------------------------------------

create table if not exists public.liquidaciones_proveedor (
    id uuid primary key default gen_random_uuid(),
    fecha timestamptz not null default now(),

    monto numeric(12,2) not null
        check (monto > 0),

    metodo_pago text,
    referencia text,
    observacion text,
    comprobante_url text,

    estado text not null default 'registrada'
        check (estado in ('registrada', 'anulada')),

    creado_por uuid not null default auth.uid()
        references auth.users(id),

    creado_en timestamptz not null default now(),

    anulada_por uuid references auth.users(id),
    anulada_en timestamptz,
    motivo_anulacion text
);

create index if not exists liquidaciones_proveedor_fecha_idx
    on public.liquidaciones_proveedor(fecha);


-- ------------------------------------------------------------
-- 5. SEGURIDAD RLS
-- ------------------------------------------------------------

alter table public.ventas enable row level security;
alter table public.detalle_ventas enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.liquidaciones_proveedor enable row level security;

drop policy if exists "ventas_select_panel" on public.ventas;
create policy "ventas_select_panel"
on public.ventas
for select
to authenticated
using (public.puede_ver_panel());

drop policy if exists "detalle_ventas_select_panel" on public.detalle_ventas;
create policy "detalle_ventas_select_panel"
on public.detalle_ventas
for select
to authenticated
using (public.puede_ver_panel());

drop policy if exists "movimientos_select_panel" on public.movimientos_inventario;
create policy "movimientos_select_panel"
on public.movimientos_inventario
for select
to authenticated
using (public.puede_ver_panel());

drop policy if exists "liquidaciones_select_panel" on public.liquidaciones_proveedor;
create policy "liquidaciones_select_panel"
on public.liquidaciones_proveedor
for select
to authenticated
using (public.puede_ver_panel());

-- No se crean políticas INSERT/UPDATE/DELETE directas.
-- Las escrituras se realizan únicamente mediante funciones seguras.

revoke all on public.ventas from anon, authenticated;
revoke all on public.detalle_ventas from anon, authenticated;
revoke all on public.movimientos_inventario from anon, authenticated;
revoke all on public.liquidaciones_proveedor from anon, authenticated;

grant select on public.ventas to authenticated;
grant select on public.detalle_ventas to authenticated;
grant select on public.movimientos_inventario to authenticated;
grant select on public.liquidaciones_proveedor to authenticated;


-- ------------------------------------------------------------
-- 6. FUNCIÓN: REGISTRAR UNA VENTA COMPLETA
-- ------------------------------------------------------------
-- Formato de p_productos:
-- [
--   {
--     "sku": "GFT-M-001-AZUL",
--     "cantidad": 1,
--     "tipo_precio": "minorista",
--     "precio_venta_unitario": 230,
--     "otros_gastos": 0
--   }
-- ]

create or replace function public.registrar_venta(
    p_productos jsonb,
    p_fecha timestamptz default now(),
    p_cliente_nombre text default null,
    p_cliente_telefono text default null,
    p_metodo_pago text default null,
    p_observacion text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_venta_id uuid;
    v_item jsonb;

    v_sku text;
    v_cantidad integer;
    v_tipo_precio text;
    v_precio_venta numeric(12,2);
    v_otros_gastos numeric(12,2);

    v_producto record;
    v_inventario record;

    v_precio_sugerido numeric(12,2);
    v_costo_proveedor_unitario numeric(12,2);

    v_stock_anterior integer;
    v_stock_nuevo integer;

    v_total_venta numeric(12,2) := 0;
    v_total_costo numeric(12,2) := 0;
    v_total_gastos numeric(12,2) := 0;
    v_total_ganancia numeric(12,2) := 0;
begin
    if auth.uid() is null then
        raise exception 'Sesión no válida.';
    end if;

    if not public.puede_editar() then
        raise exception 'No tienes permiso para registrar ventas.';
    end if;

    if p_productos is null
       or jsonb_typeof(p_productos) <> 'array'
       or jsonb_array_length(p_productos) = 0 then
        raise exception 'La venta debe contener al menos un producto.';
    end if;

    insert into public.ventas (
        fecha,
        cliente_nombre,
        cliente_telefono,
        metodo_pago,
        observacion,
        estado,
        creado_por
    )
    values (
        coalesce(p_fecha, now()),
        nullif(trim(p_cliente_nombre), ''),
        nullif(trim(p_cliente_telefono), ''),
        nullif(trim(p_metodo_pago), ''),
        nullif(trim(p_observacion), ''),
        'completada',
        auth.uid()
    )
    returning id into v_venta_id;

    for v_item in
        select value
        from jsonb_array_elements(p_productos)
    loop
        v_sku := nullif(trim(v_item ->> 'sku'), '');
        v_cantidad := coalesce((v_item ->> 'cantidad')::integer, 0);
        v_tipo_precio := coalesce(
            nullif(trim(v_item ->> 'tipo_precio'), ''),
            'personalizado'
        );
        v_precio_venta := coalesce(
            (v_item ->> 'precio_venta_unitario')::numeric,
            -1
        );
        v_otros_gastos := greatest(
            coalesce((v_item ->> 'otros_gastos')::numeric, 0),
            0
        );

        if v_sku is null then
            raise exception 'Uno de los productos no tiene SKU.';
        end if;

        if v_cantidad <= 0 then
            raise exception 'La cantidad del producto % debe ser mayor que cero.', v_sku;
        end if;

        if v_tipo_precio not in ('minorista', 'mayorista', 'personalizado') then
            raise exception 'Tipo de precio no válido para el producto %.', v_sku;
        end if;

        if v_precio_venta < 0 then
            raise exception 'El precio de venta del producto % no es válido.', v_sku;
        end if;

        select
            p.sku,
            p.codigo_modelo,
            p.nombre,
            p.color_caja,
            case
                when cardinality(p.imagenes) > 0 then p.imagenes[1]
                else null
            end as imagen_principal
        into v_producto
        from public.productos_publicos p
        where p.sku = v_sku;

        if not found then
            raise exception 'No existe el producto con SKU %.', v_sku;
        end if;

        select
            i.stock,
            i.precio_base,
            i.factor_costo,
            i.precio_minorista,
            i.precio_mayorista
        into v_inventario
        from public.inventario_privado i
        where i.sku = v_sku
        for update;

        if not found then
            raise exception 'El producto % no tiene registro de inventario.', v_sku;
        end if;

        if v_inventario.precio_base is null then
            raise exception 'El producto % no tiene precio base.', v_sku;
        end if;

        if v_inventario.factor_costo is null then
            raise exception 'El producto % no tiene factor de costo.', v_sku;
        end if;

        if v_inventario.stock < v_cantidad then
            raise exception
                'Stock insuficiente para %. Disponible: %, solicitado: %.',
                v_sku,
                v_inventario.stock,
                v_cantidad;
        end if;

        v_precio_sugerido :=
            case v_tipo_precio
                when 'mayorista' then
                    coalesce(v_inventario.precio_mayorista, v_precio_venta)
                when 'minorista' then
                    coalesce(v_inventario.precio_minorista, v_precio_venta)
                else
                    v_precio_venta
            end;

        v_costo_proveedor_unitario :=
            round(
                v_inventario.precio_base
                * v_inventario.factor_costo,
                2
            );

        insert into public.detalle_ventas (
            venta_id,
            sku,
            producto_nombre,
            codigo_modelo,
            color_caja,
            imagen_principal,
            tipo_precio,
            cantidad,
            precio_sugerido_unitario,
            precio_venta_unitario,
            precio_base_historico,
            factor_costo_historico,
            costo_proveedor_unitario,
            otros_gastos
        )
        values (
            v_venta_id,
            v_sku,
            v_producto.nombre,
            v_producto.codigo_modelo,
            v_producto.color_caja,
            v_producto.imagen_principal,
            v_tipo_precio,
            v_cantidad,
            round(v_precio_sugerido, 2),
            round(v_precio_venta, 2),
            round(v_inventario.precio_base, 2),
            v_inventario.factor_costo,
            v_costo_proveedor_unitario,
            round(v_otros_gastos, 2)
        );

        v_stock_anterior := v_inventario.stock;
        v_stock_nuevo := v_stock_anterior - v_cantidad;

        update public.inventario_privado
        set
            stock = v_stock_nuevo,
            actualizado_en = now()
        where sku = v_sku;

        insert into public.movimientos_inventario (
            sku,
            venta_id,
            tipo,
            cantidad,
            stock_anterior,
            stock_nuevo,
            observacion,
            creado_por
        )
        values (
            v_sku,
            v_venta_id,
            'venta',
            -v_cantidad,
            v_stock_anterior,
            v_stock_nuevo,
            'Descuento automático por venta',
            auth.uid()
        );

        v_total_venta :=
            v_total_venta
            + round(v_cantidad * v_precio_venta, 2);

        v_total_costo :=
            v_total_costo
            + round(v_cantidad * v_costo_proveedor_unitario, 2);

        v_total_gastos :=
            v_total_gastos
            + round(v_otros_gastos, 2);

        v_total_ganancia :=
            v_total_ganancia
            + round(
                (v_cantidad * v_precio_venta)
                - (v_cantidad * v_costo_proveedor_unitario)
                - v_otros_gastos,
                2
            );
    end loop;

    update public.ventas
    set
        total_venta = round(v_total_venta, 2),
        total_costo_proveedor = round(v_total_costo, 2),
        total_otros_gastos = round(v_total_gastos, 2),
        total_ganancia = round(v_total_ganancia, 2)
    where id = v_venta_id;

    return v_venta_id;
end;
$$;


-- ------------------------------------------------------------
-- 7. FUNCIÓN: ANULAR VENTA Y DEVOLVER STOCK
-- ------------------------------------------------------------

create or replace function public.anular_venta(
    p_venta_id uuid,
    p_motivo text
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_venta record;
    v_detalle record;
    v_stock_anterior integer;
    v_stock_nuevo integer;
begin
    if auth.uid() is null then
        raise exception 'Sesión no válida.';
    end if;

    if not public.puede_editar() then
        raise exception 'No tienes permiso para anular ventas.';
    end if;

    if nullif(trim(p_motivo), '') is null then
        raise exception 'Debes indicar el motivo de la anulación.';
    end if;

    select *
    into v_venta
    from public.ventas
    where id = p_venta_id
    for update;

    if not found then
        raise exception 'La venta no existe.';
    end if;

    if v_venta.estado = 'anulada' then
        raise exception 'La venta ya está anulada.';
    end if;

    if v_venta.estado <> 'completada' then
        raise exception 'Solo se pueden anular ventas completadas.';
    end if;

    for v_detalle in
        select sku, cantidad
        from public.detalle_ventas
        where venta_id = p_venta_id
        order by creado_en, id
    loop
        select stock
        into v_stock_anterior
        from public.inventario_privado
        where sku = v_detalle.sku
        for update;

        if not found then
            raise exception
                'No existe el inventario del producto %.',
                v_detalle.sku;
        end if;

        v_stock_nuevo := v_stock_anterior + v_detalle.cantidad;

        update public.inventario_privado
        set
            stock = v_stock_nuevo,
            actualizado_en = now()
        where sku = v_detalle.sku;

        insert into public.movimientos_inventario (
            sku,
            venta_id,
            tipo,
            cantidad,
            stock_anterior,
            stock_nuevo,
            observacion,
            creado_por
        )
        values (
            v_detalle.sku,
            p_venta_id,
            'anulacion_venta',
            v_detalle.cantidad,
            v_stock_anterior,
            v_stock_nuevo,
            'Devolución automática por anulación',
            auth.uid()
        );
    end loop;

    update public.ventas
    set
        estado = 'anulada',
        anulada_por = auth.uid(),
        anulada_en = now(),
        motivo_anulacion = trim(p_motivo)
    where id = p_venta_id;
end;
$$;


-- ------------------------------------------------------------
-- 8. FUNCIÓN: REGISTRAR LIQUIDACIÓN AL PROVEEDOR
-- ------------------------------------------------------------

create or replace function public.registrar_liquidacion_proveedor(
    p_monto numeric,
    p_fecha timestamptz default now(),
    p_metodo_pago text default null,
    p_referencia text default null,
    p_observacion text default null,
    p_comprobante_url text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_id uuid;
begin
    if auth.uid() is null then
        raise exception 'Sesión no válida.';
    end if;

    if not public.puede_editar() then
        raise exception 'No tienes permiso para registrar liquidaciones.';
    end if;

    if p_monto is null or p_monto <= 0 then
        raise exception 'El monto debe ser mayor que cero.';
    end if;

    insert into public.liquidaciones_proveedor (
        fecha,
        monto,
        metodo_pago,
        referencia,
        observacion,
        comprobante_url,
        creado_por
    )
    values (
        coalesce(p_fecha, now()),
        round(p_monto, 2),
        nullif(trim(p_metodo_pago), ''),
        nullif(trim(p_referencia), ''),
        nullif(trim(p_observacion), ''),
        nullif(trim(p_comprobante_url), ''),
        auth.uid()
    )
    returning id into v_id;

    return v_id;
end;
$$;


-- ------------------------------------------------------------
-- 9. FUNCIÓN: ANULAR LIQUIDACIÓN
-- Solo administradores, porque afecta el saldo entregado.
-- ------------------------------------------------------------

create or replace function public.anular_liquidacion_proveedor(
    p_liquidacion_id uuid,
    p_motivo text
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if auth.uid() is null then
        raise exception 'Sesión no válida.';
    end if;

    if not public.es_administrador() then
        raise exception 'Solo un administrador puede anular una liquidación.';
    end if;

    if nullif(trim(p_motivo), '') is null then
        raise exception 'Debes indicar el motivo de la anulación.';
    end if;

    update public.liquidaciones_proveedor
    set
        estado = 'anulada',
        anulada_por = auth.uid(),
        anulada_en = now(),
        motivo_anulacion = trim(p_motivo)
    where id = p_liquidacion_id
      and estado = 'registrada';

    if not found then
        raise exception 'La liquidación no existe o ya está anulada.';
    end if;
end;
$$;


-- ------------------------------------------------------------
-- 10. RESUMEN FINANCIERO PARA EL DASHBOARD
-- ------------------------------------------------------------

create or replace function public.obtener_resumen_financiero(
    p_desde timestamptz default null,
    p_hasta timestamptz default null
)
returns table (
    ventas_completadas bigint,
    productos_vendidos bigint,
    ingresos numeric,
    costo_proveedor_generado numeric,
    otros_gastos numeric,
    ganancia_real numeric,
    pagado_proveedor numeric,
    saldo_pendiente_proveedor numeric
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if auth.uid() is null or not public.puede_ver_panel() then
        raise exception 'No tienes permiso para ver el resumen financiero.';
    end if;

    return query
    with resumen_ventas as (
        select
            count(*)::bigint as ventas_completadas,
            coalesce(sum(v.total_venta), 0)::numeric as ingresos,
            coalesce(sum(v.total_costo_proveedor), 0)::numeric
                as costo_proveedor_generado,
            coalesce(sum(v.total_otros_gastos), 0)::numeric as otros_gastos,
            coalesce(sum(v.total_ganancia), 0)::numeric as ganancia_real
        from public.ventas v
        where v.estado = 'completada'
          and (p_desde is null or v.fecha >= p_desde)
          and (p_hasta is null or v.fecha < p_hasta)
    ),
    resumen_productos as (
        select
            coalesce(sum(d.cantidad), 0)::bigint as productos_vendidos
        from public.detalle_ventas d
        join public.ventas v on v.id = d.venta_id
        where v.estado = 'completada'
          and (p_desde is null or v.fecha >= p_desde)
          and (p_hasta is null or v.fecha < p_hasta)
    ),
    resumen_pagos as (
        select
            coalesce(sum(l.monto), 0)::numeric as pagado_proveedor
        from public.liquidaciones_proveedor l
        where l.estado = 'registrada'
    )
    select
        rv.ventas_completadas,
        rp.productos_vendidos,
        round(rv.ingresos, 2),
        round(rv.costo_proveedor_generado, 2),
        round(rv.otros_gastos, 2),
        round(rv.ganancia_real, 2),
        round(rpg.pagado_proveedor, 2),
        round(
            (
                select coalesce(sum(v2.total_costo_proveedor), 0)
                from public.ventas v2
                where v2.estado = 'completada'
            ) - rpg.pagado_proveedor,
            2
        )
    from resumen_ventas rv
    cross join resumen_productos rp
    cross join resumen_pagos rpg;
end;
$$;


-- ------------------------------------------------------------
-- 11. PERMISOS DE FUNCIONES
-- ------------------------------------------------------------

revoke all on function public.registrar_venta(
    jsonb, timestamptz, text, text, text, text
) from public, anon;

revoke all on function public.anular_venta(
    uuid, text
) from public, anon;

revoke all on function public.registrar_liquidacion_proveedor(
    numeric, timestamptz, text, text, text, text
) from public, anon;

revoke all on function public.anular_liquidacion_proveedor(
    uuid, text
) from public, anon;

revoke all on function public.obtener_resumen_financiero(
    timestamptz, timestamptz
) from public, anon;

grant execute on function public.registrar_venta(
    jsonb, timestamptz, text, text, text, text
) to authenticated;

grant execute on function public.anular_venta(
    uuid, text
) to authenticated;

grant execute on function public.registrar_liquidacion_proveedor(
    numeric, timestamptz, text, text, text, text
) to authenticated;

grant execute on function public.anular_liquidacion_proveedor(
    uuid, text
) to authenticated;

grant execute on function public.obtener_resumen_financiero(
    timestamptz, timestamptz
) to authenticated;


-- Las secuencias identity no deben ser accesibles directamente
-- porque los INSERT se realizan desde funciones SECURITY DEFINER.
revoke all on all sequences in schema public from anon, authenticated;


commit;


-- ============================================================
-- VERIFICACIÓN
-- Ejecutar después del bloque anterior.
-- ============================================================

select
    n.nspname as esquema,
    c.relname as tabla,
    c.relrowsecurity as rls_habilitado,
    c.relforcerowsecurity as rls_forzado
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname in (
      'ventas',
      'detalle_ventas',
      'movimientos_inventario',
      'liquidaciones_proveedor'
  )
  and c.relkind = 'r'
order by c.relname;

select
    schemaname,
    tablename,
    policyname,
    roles,
    cmd
from pg_policies
where schemaname = 'public'
  and tablename in (
      'ventas',
      'detalle_ventas',
      'movimientos_inventario',
      'liquidaciones_proveedor'
  )
order by tablename, policyname;
